---
title: "ENTREGABLE 3"
author: "Valverde, Andrea"
date: "2024-11-13"
output: html_document
---

```{r}
library(rio)
edu=import("Educacion.xls")
emple=import("empleo.xls")
tec=import("tecnologia.xls")
vivi=import("vivienda.xls")
salud=import("salud.xls")
```

```{r}
library(dplyr)
summary(edu)
```
```{r}
library(scales)
edu = edu %>%
  mutate(i_edu = round(rescale(matricula_edu22, to = c(0, 5)),0))
```

```{r}
summary(salud)
```
```{r}
salud = salud %>%
  mutate(i_salud = round(rescale(desnut21, to = c(0, 5)),0))
```

```{r}
library(dplyr)
salud <- salud %>%
  mutate(i_salud = case_when( i_salud == 0 ~ 5,
                            i_salud == 1 ~ 4,
                            i_salud == 2 ~ 3,
                            i_salud == 3 ~ 2,
                            i_salud== 4 ~ 1,
                            i_salud == 5 ~ 0))
```


```{r}
summary(tec)
```
```{r}
tec = tec %>%
  mutate(i_tec = round(rescale(telef_fija22, to = c(0, 5)),0))
```

```{r}
summary(vivi)
```
```{r}
vivi = vivi %>%
  mutate(i_vivi = round(rescale(por_elec22, to = c(0, 5)),0))
```

```{r}
summary(emple)
```

```{r}
# Aplicar el logaritmo natural
emple$f_laboral22_log <- log(emple$f_laboral22)
```

```{r}
summary(emple$f_laboral22_log)
```

```{r}
emple = emple %>%
  mutate(i_emple = round(rescale(f_laboral22_log, to = c(0, 5)),0))
```

# CREANDO NUEVO DATAFRAME

```{r}
emple_columna <- emple[, c("Country Name", "i_emple")]
edu_columna <- edu[, c("Country Name", "i_edu")]
salud_columna <- salud[, c("Country Name", "i_salud")]
tec_columna <- tec[, c("Country Name", "i_tec")]
vivi_columna <- vivi[, c("Country Name", "i_vivi")]
```

## MERGE

```{r}
edu_emple=merge(edu_columna,emple_columna,by="Country Name")
 edu_emple
```
```{r}
ee_tec=merge(edu_emple,tec_columna,by="Country Name")
 ee_tec
```

```{r}
eet_vivi=merge(ee_tec,vivi_columna,by="Country Name")
 eet_vivi
```

```{r}
indicador=merge(eet_vivi,salud_columna,by="Country Name")
 indicador
```

## FILTRO DE DATOS QUE QUEREMOS

```{r}
# Define los nombres específicos que deseas seleccionar
nombres_especificos <- c("Albania","Andorra","Austria","Belarús","Bélgica","Bosnia y Herzegovina","Bulgaria","Croacia","Chipre","República Checa","Dinamarca","Estonia","Finlandia","Francia","Alemania","Grecia","Hungría","Islandia","Irlanda","Italia","Kosovo","Letonia","Liechtenstein","Lituania","Luxemburgo","Malta","República de Moldova","Mónaco","Montenegro","Países Bajos","Macedonia del Norte","Noruega","Polonia","Portugal","Rumania","San Marino","Serbia","República Eslovaca","Eslovenia","España","Suecia", "Suiza","Ucrania", "Reino Unido", "Argentina","Bolivia","Brasil","Chile","Colombia","Ecuador","Guyana","Paraguay","Perú","Suriname","Uruguay","Venezuela","Guatemala","México","Panamá","Costa Rica","Nicaragua","Honduras","El Salvador","Belice","Cuba","República Dominicana","Haití")

# Filtra la base de datos 'indicador' usando la columna 'names country'
indicador_filtrado <- subset(indicador, `Country Name` %in% nombres_especificos)

# Muestra el data frame filtrado
print(indicador_filtrado)
```

```{r}
indicador_filtrado=indicador_filtrado %>%
  mutate(suma = rowSums(select(., i_edu, i_salud, i_emple, i_tec, i_vivi), na.rm = TRUE))
```

```{r}
indicador_filtrado <- indicador_filtrado %>%
  rename(PAIS = `Country Name`)
```


#IMPORTANDO DATA

```{r}
EU_AL=import("EU_AL.xlsx")
```

```{r}
str(EU_AL)
```
```{r}
EU_AL <- EU_AL %>%
  mutate(across(c(PBI_perk, tasa_infla), as.numeric))
```
```{r}
str(EU_AL)
```


```{r}
data=merge(indicador_filtrado,EU_AL,by="PAIS")
 data
```

```{r}
summary(data$suma, na.rm=T)
```


```{r}
library(writexl)
write_xlsx(data, "data_completa.xlsx")
```

```{r}
Desc_data = data %>% 
  summarise(
    Media = mean(data$suma,na.rm=T), 
    Mediana = median(data$suma,na.rm=T), 
    Desviacion = sd(data$suma,na.rm=T), 
    Minimo = min(data$suma,na.rm=T), 
    Maximo = max(data$suma,na.rm=T),
    Q1 = quantile(data$suma, 0.25,na.rm=T),
    Q3 = quantile(data$suma, 0.75,na.rm=T))
```

```{r}
library(knitr)
kable(Desc_data, caption = "Analisis Descriptivo del puntaje por calidad de vida segun pais")
```


```{r}
data %>% 
  ggplot(aes(x = PAIS, y = suma)) + 
  geom_bar(stat = "identity", color = "blue", fill = "#00BFFF", width = 0.6) + 
  ggtitle("Puntaje de calidad de vida según país") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8))
```

```{r}
data =data|>
  mutate(cal_vida = case_when(
    suma < 5 ~ "Muy Baja",
    suma >= 5 & suma < 10 ~ "Baja",
    suma >= 10 & suma < 15 ~ "Media",
    suma >= 15 & suma < 20 ~ "Alta",
    suma >= 20 ~ "Muy Alta"
  ))
head(data)
```

```{r}
library(ggplot2)
ggplot(data, aes(x = factor(cal_vida, levels = c("Muy Baja", "Baja", "Media", "Alta", "Muy Alta")), 
                 y = suma, 
                 color = cal_vida)) + 
  geom_boxplot() + 
  geom_jitter(shape = 16, position = position_jitter(0.3), alpha = 0.6) +  # Agrega los puntos
  theme_classic() + 
  expand_limits(y = c(0, 25)) +  # Ajusta el rango de valores en el eje Y
  ggtitle("Boxplot de la Suma por Calificación de Vida") +  # Título
  xlab("Nivel de Calidad de Vida") +  # Etiqueta eje X
  ylab("Suma")  # Etiqueta eje Y

```

```{r}
data %>% 
  ggplot(aes(x = factor(cal_vida, levels = c("Muy Baja", "Baja", "Media", "Alta", "Muy Alta")))) + 
  geom_bar(aes(fill = cal_vida), color = "black") +  # Asignar colores distintos por nivel
  ggtitle("Conteo de calificación de vida por nivel") +  # Título
  xlab("Nivel de Calificación de Vida") +  # Etiqueta eje X
  ylab("Conteo") +  # Etiqueta eje Y
  scale_fill_manual(values = c("Muy Baja" = "#FF6347",  # Rojo
                              "Baja" = "#FF8C00",    # Naranja
                              "Media" = "#FFD700",   # Amarillo
                              "Alta" = "#32CD32",    # Verde
                              "Muy Alta" = "#1E90FF")) +  # Azul
  theme_minimal() +  # Tema minimalista
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotar etiquetas del eje X
```









