---
title: "Entregable3_corregido"
output: html_document
date: "2024-11-16"
---

```{r}
library(rio)
edu=import("Educacion.xls")
emple=import("empleo.xls")
tec=import("tecnologia.xls")
vivi=import("vivienda.xls")
salud=import("salud.xls")
```

```{r}
library(dplyr)
summary(salud)
```

```{r}
salud$desnut21_rec = 51-salud$desnut21 + 2.5
summary(salud)
```


```{r}
library(dplyr)
summary(edu)
```
```{r}
summary(tec)
```
```{r}
summary(vivi)
```
```{r}
summary(emple)
```
```{r}
# Aplicar el logaritmo natural
emple$f_laboral22_log <- log(emple$f_laboral22)
summary(emple)
```
```{r}
salud_apoyo <- salud[, c("Country Name", "desnut21_rec")]
emple_apoyo <- emple[, c("Country Name", "f_laboral22_log")]
```

# MERGE
```{r}
edu_emple=merge(edu,emple_apoyo,by="Country Name")
 edu_emple
```
```{r}
ee_tec=merge(edu_emple,tec,by="Country Name")
 ee_tec
```
```{r}
eet_vivi=merge(ee_tec,vivi,by="Country Name")
 eet_vivi
```
```{r}
indicador=merge(eet_vivi,salud_apoyo,by="Country Name")
 indicador
```

```{r}
indicador <- indicador %>%
  rename(PAIS = `Country Name`)
```


```{r}
str(indicador)
```

```{r}
# Define los nombres específicos que deseas seleccionar
nombres_especificos <- c("Albania","Andorra","Austria","Belarús","Bélgica","Bosnia y Herzegovina","Bulgaria","Croacia","Chipre","República Checa","Dinamarca","Estonia","Finlandia","Francia","Alemania","Grecia","Hungría","Islandia","Irlanda","Italia","Kosovo","Letonia","Liechtenstein","Lituania","Luxemburgo","Malta","República de Moldova","Mónaco","Montenegro","Países Bajos","Macedonia del Norte","Noruega","Polonia","Portugal","Rumania","San Marino","Serbia","República Eslovaca","Eslovenia","España","Suecia", "Suiza","Ucrania", "Reino Unido", "Argentina","Bolivia","Brasil","Chile","Colombia","Ecuador","Guyana","Paraguay","Perú","Suriname","Uruguay","Venezuela","Guatemala","México","Panamá","Costa Rica","Nicaragua","Honduras","El Salvador","Belice","Cuba","República Dominicana","Haití")

# Filtra la base de datos 'indicador' usando la columna 'names country'
indicador_filtrado <- subset(indicador, `PAIS` %in% nombres_especificos)

# Muestra el data frame filtrado
print(indicador_filtrado)
```

```{r}
str (indicador_filtrado)
```

```{r}
datos_std <- as.data.frame(scale(indicador_filtrado[, c("matricula_edu22", "f_laboral22_log","telef_fija22","por_elec22","desnut21_rec")]))
print(datos_std)
```

```{r}
datos_std <- na.omit(datos_std)
indicador_filtrado <- na.omit(indicador_filtrado)
```

```{r}
library(psych)
library(ggplot2)
library(corrplot)
```

```{r}
kmo_result <- KMO(datos_std)
print(kmo_result)
```

```{r}
bartlett_result <- cortest.bartlett(cor(datos_std), n = nrow(datos_std))
print(bartlett_result)
```


```{r}
cor_matrix <- cor(datos_std)
corrplot(cor_matrix, method = "color")
```


```{r}
cortest.bartlett(cor_matrix,n=nrow(datos_std))$p.value>0.05
```

```{r}
fa_parallel <- fa.parallel(datos_std, fm = "ml", fa = "fa")
```


```{r}
fa.parallel(datos_std, fa = 'fa',correct = T,plot = F)
```

```{r}
fa_result <- fa(datos_std, nfactors = 1, rotate = "varimax", fm = "ml")
print(fa_result)
```

```{r}
fa.diagram(fa_result)
```

```{r}
print(fa_result$loadings,cutoff = 0.5)
```

```{r}
sort(fa_result$communality)
```

```{r}
sort(fa_result$complexity)
```

```{r}
fa_result$TLI
```

```{r}
fa_result$rms
```

```{r}
fa_result$RMSEA
```

```{r}
fa_result$BIC
```

```{r}
as.data.frame(fa_result$scores)%>%head()
```

```{r}
factor_scores <- factor.scores(datos_std, fa_result)
datos_std$factor_score <- factor_scores$scores
```

```{r}
# Agregar columnas estandarizadas al data frame original
indicador_filtrado$i_edu <- datos_std$matricula_edu22
indicador_filtrado$i_emple <- datos_std$f_laboral22_log
indicador_filtrado$i_tec <- datos_std$telef_fija22
indicador_filtrado$i_vivi <- datos_std$por_elec22
indicador_filtrado$i_salud <- datos_std$desnut21_rec
indicador_filtrado$cal_vida <- datos_std$factor_score
```


```{r}
EU_AL=import("EU_AL.xlsx")
```

```{r}
str(EU_AL)
```

```{r}
EU_AL <- EU_AL %>%
  mutate(across(c(PBI_perk, tasa_infla), as.numeric))
```

```{r}
str(EU_AL)
```

```{r}
data=merge(indicador_filtrado,EU_AL,by="PAIS")
 data
```

```{r}
summary(data$cal_vida)
```

```{r}
library(DescTools)

allStats=c(summary(data$cal_vida),
  sd=sd(data$cal_vida),
  skew=Skew(data$cal_vida),
  kurt=Kurt(data$cal_vida),
  cv=CoefVar(data$cal_vida))
allStats
```

```{r}
library(ggplot2)

barras_vida=ggplot(data=data,
            aes(x=cal_vida))
histogram= barras_vida + geom_histogram(aes(y = after_stat(density)),
                 colour = 1, fill = "white",bins=10) +  
    stat_function(fun = dnorm,
                  args = list(mean = allStats['Mean'],
                              sd = allStats['sd']),col='red')
    
histogram
```

```{r}
library(ggplot2)

boxvida=ggplot(data=data,
            aes(y=cal_vida))
boxplot=barras_vida + geom_boxplot()

boxplot
```

```{r}
library(ggplot2)
data |>
  ggplot(aes(x = PAIS, y = cal_vida)) + 
  geom_bar(stat = "identity", color = "blue", fill = "#00BFFF", width = 0.6) + 
  ggtitle("Puntaje de calidad de vida según país") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8))
```


```{r}
ggplot(data, aes(x=reorder(PAIS,cal_vida), y=cal_vida), fill = select) + 
  geom_bar(stat = "identity", width = 0.8) +
  coord_flip()+
  
  labs(title = "Puntaje de calidad de vida por País",
       subtitle = "Europa y Latinoamérica",
       x = " ",
       y = "Escala - 4- 5") +

    geom_hline(yintercept = mean(data$cal_vida) ,linetype="dashed", color="blue",size=1)+
  
    ylim(-4, 2) +

    geom_text(aes(label=paste0(round(cal_vida,0),"%")), vjust=0.5, hjust = 1.2,color="green", size=2)+
  theme(axis.text.y = element_text(size = 5),  plot.margin = margin(2, 2, 2, 2))
```




# ANÁLISIS DE CORRELACIÓN ENTRE VARIABLES NUMÉRICAS
## calidad de vida con pobla
```{r}
library(ggrepel)
base1=ggplot(data=data, aes(x=cal_vida, y=pobla))
scatter = base1 + geom_point()
scatterText = scatter + geom_text_repel(aes(label=PAIS),size=3)
scatterText
```

```{r}
f1=formula(~cal_vida + pobla)
```

```{r}
pearsonf1=cor.test(f1,data=data)[c('estimate','p.value')]
pearsonf1
```

```{r}
spearmanf1=cor.test(f1,data=data,method='spearman',exact=F)[c('estimate','p.value')]
spearmanf1
```

## calidad de vida y PBI per cápita
```{r}
library(ggrepel)
base2=ggplot(data=data, aes(x=cal_vida, y=PBI_perk))
scatter = base2 + geom_point()
scatterText = scatter + geom_text_repel(aes(label=PAIS),size=3)
scatterText
```

```{r}
f2=formula(~cal_vida + PBI_perk)
```

```{r}
pearsonf2=cor.test(f2,data=data)[c('estimate','p.value')]
pearsonf2
```

```{r}
spearmanf2=cor.test(f1,data=data,method='spearman',exact=F)[c('estimate','p.value')]
spearmanf2
```
## calidad de vida y tasa de inflación
```{r}
library(ggrepel)
base3=ggplot(data=data, aes(x=,cal_vida, y=tasa_infla))
scatter = base3 + geom_point()
scatterText = scatter + geom_text_repel(aes(label=PAIS),size=2)
scatterText
```


```{r}
f3=formula(~ cal_vida  + tasa_infla )
```

```{r}
pearsonf3=cor.test(f3,data=data)[c('estimate','p.value')]
pearsonf3
```
## calidad de vida y división administrativa
```{r}
library(ggrepel)
base4=ggplot(data=data, aes(x=cal_vida, y=div_admi))
scatter = base4 + geom_point()
scatterText = scatter + geom_text_repel(aes(label=PAIS),size=2)
scatterText
```

```{r}
f4=formula(~ cal_vida + div_admi )
```

```{r}
pearsonf4=cor.test(f4,data=data)[c('estimate','p.value')]
pearsonf4
```

# ANÁLISIS DE CORRELACIÓN ENTRE VARIABLE NUMÉRICA CON CATEGÓRICA 

```{r}
data$cam <- factor(data$cam, levels = c("unicameral", "bicameral"))
str(data$cam)
```

```{r}
table(data$cam)
```


```{r}
data$reg_pol <- factor(data$reg_pol, levels = c("Democracia parlamentaria","Republica presidencial","Monarquia constitucional",  "Republica federal","Republica parlamentaria federal", "Republica parlamentaria", "Republica semipresidencial", "Estado comunista"))
str(data$reg_pol)
```

```{r}
table(data$reg_pol)
```


```{r}
str(data)
```

```{r}
base5 <- ggplot(data = data, aes(x = reg_pol, y = cal_vida))

base5 + 
  geom_boxplot(notch = TRUE) + 
  geom_jitter(color = "black", size = 0.4, alpha = 0.9) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
f5=formula(cal_vida~reg_pol)
```

```{r}
(student_T=t.test(f5,data=data)[c('estimate','p.value')])
```






```{r}
base6 <- ggplot(data = data, aes(x = cam, y = cal_vida))

base6 + 
  geom_boxplot(notch = TRUE) + 
  geom_jitter(color = "black", size = 0.4, alpha = 0.9) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
f6=formula(cal_vida~cam)
```

```{r}
(student_T=t.test(f6,data=data)[c('estimate','p.value')])
```

```{r}
(Mann_Whitnery=wilcox.test(f6,data=data,exact=F)['p.value'])
```

```{r}
base7=ggplot(data=data, aes(x=CONTINENTE, y=cal_vida))
base7 + geom_boxplot(notch = T) +  geom_jitter(color="black", size=0.4, alpha=0.9) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
f7=formula(cal_vida~CONTINENTE)
```

```{r}
(student_T=t.test(f7,data=data)[c('estimate','p.value')])
```

```{r}
(Mann_Whitnery=wilcox.test(f7,data=data,exact=F)['p.value'])
```

# MODELO LINEAL MULTIPLE

```{r}
modelo_lmultiple <- lm(cal_vida ~ pobla + PBI_perk + tasa_infla + div_admi, data = data)

summary(modelo_lmultiple)
```


# MODELO LOGÍSTICO MULTINOMIAL
```{r}
library(nnet)
mod_lgmulti <- multinom(cal_vida ~ pobla + PBI_perk + tasa_infla + div_admi, data = data)
summary(mod_lgmulti)
```






















































