---
title: "R Notebook"
output: html_notebook
---



```{r}
link="https://docs.google.com/spreadsheets/d/1cxXiYauDGUU6O6z1KZlb2VIEUqwh_oXbI1pkJfshJrs/pub?gid=687220636&single=true&output=csv"

disca=read.csv(link)
```

```{r}
head(disca,10)
```


```{r}
disca_ok=disca[7:1387,2:4]
```

```{r}
names(disca_ok)=c("area","lugar","pct")
row.names(disca_ok)=NULL
```


```{r}
disca_ok$lugar[grep("AREA",disca_ok$area)]
```

```{r}
clean_disca=data.frame(disca_ok$lugar[grep("AREA",disca_ok$area)])
names(clean_disca)="depaprov"
```


```{r}
clean_disca$Total=disca_ok$lugar[grep("Total",disca_ok$area)][1:196]
  
```


```{r}
clean_disca$discaPct=disca_ok$pct[grep("algun",disca_ok$area)][1:196]
```



```{r}
clean_disca$depaprov[-grep(":",clean_disca$depaprov)]
```
```{r}
clean_disca[clean_disca$depaprov=="Provincia Constitucional del Callao","depaprov"]="Callao, provincia: Callao"
clean_disca[clean_disca$depaprov=="Madre de Dios prov. de Tambopata","depaprov"]="Madre de Dios, provincia: Tambopata"
clean_disca[clean_disca$depaprov=="Madre de Dios prov. de Manu","depaprov"]="Madre de Dios, provincia: Manu"
clean_disca[clean_disca$depaprov=="Madre de Dios prov. de Tahuamanu","depaprov"]="Madre de Dios, provincia: Tahuamanu"

```
```{r}
library(stringr)
str_split_fixed(clean_disca$depaprov, ",|:", 3)
```


```{r}



clean_disca[c(4,5,6)]=as.data.frame(str_split_fixed(clean_disca$depaprov, ",|:", 3))
names(clean_disca)[c(4,5,6)]= c("region", "nn","provincia")
```

```{r}
lapply(clean_disca[,c(4,6)],trimws,whitespace = "[\\h\\v]")
```

```{r}
clean_disca[,c(4,6)]=lapply(clean_disca[,c(4,6)],trimws,whitespace = "[\\h\\v]")
```

```{r}
clean_disca$Total=readr::parse_number(clean_disca$Total,locale = readr::locale(decimal_mark = ".", grouping_mark = " "))
clean_disca$Total
```
```{r}
clean_disca$discaPct=readr::parse_number(clean_disca$discaPct,locale = readr::locale(decimal_mark = ","))
clean_disca$discaPct
```
```{r}
str(clean_disca)

```

```{r}
clean_disca=clean_disca[,c(4,6,2,3)]
```


```{r}
table(clean_disca$region)
```

```{r}
clean_disca[clean_disca$region=="LA LBERTAD","region"]="LA LIBERTAD"
```

```{r}
table(clean_disca$provincia)
```

```{r}
library(scraEP)

clean_disca[,c(1,2)]=lapply(clean_disca[,c(1,2)],unaccent)
```


```{r}
linkEG="https://docs.google.com/spreadsheets/d/1W6eKpxb1l2l__OHeQNU6obs0JwfaWc2saGehcviVkck/pub?gid=945804701&single=true&output=csv"
elec=read.csv(linkEG)
```



```{r}
names(elec)
```
```{r}
elec[,c(1,2)]=lapply(elec[,c(1,2)],unaccent)
```

```{r}
names(elec)=gsub("X..","pct_",names(elec))
names(elec)
```
```{r}
names(elec)=scraEP::unaccent(names(elec))
names(elec)
```
```{r}
table(elec$Tipo.Organizacion.Politica)
```
```{r}
elec$Tipo.Organizacion.Politica=NULL
```


```{r}
table(elec$Organizacion.Politica)
```


```{r}
gsub("\\W+","_",elec$Organizacion.Politica)
```


```{r}
elec$Organizacion.Politica=gsub("\\W+","_",elec$Organizacion.Politica)
```


```{r}
str(elec)
```

```{r}
elec[,c(3:11,13,14)]
```

```{r}
elec[,c(3:11,13,14)]=lapply(elec[,c(3:11,13,14)],readr::parse_number,locale = readr::locale(decimal_mark = "."))

str(elec)
```

```{r}
elec_w=reshape(elec, idvar = names(elec)[1:11], timevar = "Organizacion.Politica", direction = "wide")
```


```{r}
names(elec_w)[c(1,2)]=c('region',"provincia")
```

```{r}
dengue=read.csv("datos_abiertos_vigilancia_dengue.csv")
names(dengue)
```


```{r}
names(dengue)[1]="region"
```

```{r}
dengue[,c(1,2)]=lapply(dengue[,c(1,2)],unaccent)
```

```{r}
table(dengue$ano)
```

```{r}
dengue[dengue$ano=='III',]
```
```{r}
table(dengue$region)
```
```{r}
dengue[dengue$region%in% c('\\N',"A"),]
```
```{r}
dengue21=dengue[dengue$ano==2021,]
```

```{r}
table(dengue21$enfermedad)
```
```{r}
aggregate(data=dengue21, enfermedad~region + provincia,length)
```

```{r}
dengue21[dengue21$provincia=="\\N",]
```

```{r}
dengue21=dengue21[dengue21$provincia!="\\N",]
```


```{r}
dengue21Prov=aggregate(data=dengue21, enfermedad~region + provincia,length)
```


```{r}
names(dengue21Prov)
```
```{r}
names(dengue21Prov)[3]='casosDengue'
```

```{r}
elec_w[duplicated(elec_w$provincia),]
```

```{r}
clean_disca[duplicated(clean_disca$provincia),]
```

```{r}
clean_disca[,c(1,2)]=lapply(clean_disca[,c(1,2)],toupper)
```

```{r}
setdiff(dengue21Prov$provincia,clean_disca$provincia)
```
```{r}
setdiff(elec_w$provincia,clean_disca$provincia)
```
```{r}
setdiff(clean_disca$provincia,elec_w$provincia)
```

```{r}
clean_disca[clean_disca$provincia=="ANTONIO RAYMONDI",'provincia']="ANTONIO RAIMONDI"
elec_w[elec_w$provincia=="NASCA",'provincia']="NAZCA"
```


```{r}
allData=merge(clean_disca,elec_w,by = 'provincia')
head(allData)
```

```{r}
allData=merge(allData,dengue21Prov,all.x = T,by='provincia')
```

```{r}
allData[is.na(allData)] <- 0
```

```{r}
write.csv(allData,"allData.csv",row.names = F)
```

